### ISSUE TITLE
see documentation

### ISSUE THREAD

**Issue by danhellem** [CanarysAutomations/pr-update-work-item-state#29]
FYI, this already works if you use the right syntax and the app

https://docs.microsoft.com/en-us/azure/devops/boards/github/link-to-from-github?view=azure-devops#use-ab-mention-to-link-from-github-to-azure-boards-work-items

![image](https://user-images.githubusercontent.com/10525048/97459063-94108a00-18f8-11eb-9451-090bc5f10022.png)

**Comment by vaishnav-canarys** [comment]
Hi Dan, thank you for your feedback. We have tested the supported keywords present in the document which you shared. These keywords help transition a work item to a Done state, when linked with a commit or a pull request. However we are aiming to achieve transitioning a work item to its next state i.e **ToDo -> Doing**, **New-> Active** etc.  We also added a check to see if pull request merge was successful or not with our latest release, the work item will transition to its next state only when the pull request merge is successful. The need of this action rose out of a particular end user requirement. 
We would be grateful if you could further test this action out and provide additional feedback


**Workflow steps**

1. Gets the workitem Id from the pull request 
2. Gets the pull request merge status 
3. Gets the current state of the workitem id
4. Verifies the current state of the workitem id, matches with the closed state [Input Given by the user]. If the current state matches with the closed state, the action exits.
If it doesn't match, the PR merge status is checked
5. IF PR merge was successful, the work item's state is updated to its next state and the workitem's description is updated to reflect the successful merge. If not
 successful, the workitem's state remains the same and the description will updated to reflect the non-successful merge.
